version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-05-19T18-20-59Z
  command: server /data --console-address ":9001"
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
services:
  minio:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9090:9000"
      - "9191:9001"
    depends_on:
      - minio

  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "8232:80"
    environment:
      MINIO_USER: minioadmin
      MINIO_PASSWORD: minioadmin

volumes:
  data1-1:
  data1-2: